# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/buster64"
  config.vm.define "ndn-tutorial" do |tutorial|
  end
  config.vm.provider "virtualbox" do |vb|
    vb.name = "NDN-Tutorial"
    vb.gui = true
    vb.memory = 1024
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--vram", "32"]

  end
  config.vm.synced_folder '../', '/ndn-tutorial', type: "virtualbox"
  config.vm.hostname = "ndn-tutorial"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", reboot: true
end
